# -*- coding: utf-8 -*-
"""Project1_OOPD.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EtPTfot-3gUqSXJT5ZfsM4TGqrdsXFqg
"""

def train_information(c):
  for i in train_details:
    if c in i:
      train_id = i[0]
      train_name = i[1]
      departure = i[2]
      arrival = i[3]
      source = i[4]
      destination = i[5]
      fare = i[6]
      print("\nTrain Information:")
      print("Train ID: " + train_id)
      print("Name of Train: " + train_name)
      print("Starting Station: " + source)
      print("Departure Time: " + departure)
      print("Destination: " + destination)
      print("Arrival Time: " + arrival)
      print("Train fare: " + str(fare))
      print("\n")
      break
    else:
      print("No train exist having Train name or PNR number:",c)
      print("\n")

def Passenger_data():
  details = []
  last_passenger_id = passenger_details[len(passenger_details)-1][0]
  passenger_id = last_passenger_id + 1
  details.append(passenger_id)
  name = input("Enter passenger name \n")
  details.append(name)
  age = input("Enter passenger age \n")
  details.append(age)
  phone = input("Enter passenger phone number \n")
  details.append(phone)
  passenger_details.append(details)
  return passenger_id

def check_availability(c):
  train_id=''
  for i in train_details:
    if c in i:
      train_id=i[0]
      break
  for i in availability:
    # print(i)
    if train_id in i:
      return i[2]
  return -1

def Booking():
  c=input("Enter train name or PNR number for booking")
  train_id,cost='',0
  for i in train_details:
    if c in i:
      train_id=i[0]
      cost=i[6]
      break
  if train_id=='':
    print("No train exist having Train name or PNR number:",c)
    return 
  if check_availability(train_id)>0:
    p_id=Passenger_data()
    print("You have to pay",cost,". Can we proceed for payment?")
    yes_no=input()
    if yes_no in ['Yes','yes','y','Y']:
      Payment(p_id,cost)
    else:
      print("No booking done")
      return
    last_booking_id=bookings[len(bookings)-1][0]
    #for seat number
    seat_no=1
    for i in bookings:
      if i[1]==train_id:
        seat_no=max(i[3],seat_no)
    bookings.append([last_booking_id+1,train_id,p_id,seat_no+1])
    print("Your Booking is Completed Successfully")
    print("Your booking id is",last_booking_id+1)
    print("You have booked the train having PNR", train_id)
    print("Your seat number is",seat_no+1)
    print("Happy Journey!!")
    for i in availability:
      if train_id in i:
        i[2]-=1
        break
  else:
    print("No vacancy available in this train")
  return

def Payment(passenger_id,cost):
  last_payment_id=payment[len(payment)-1][0]
  payment.append([last_payment_id+1,passenger_id,cost])
  print("Payment Successfully Done!!")
  return

def cancelbook(book_id):
  pid,flag=0,0
  train_id=-1
  for i in bookings:
    if int(book_id)==i[0]:
      pid=i[2]
      flag=1
      train_id=i[1]
  if flag==0:
    print("This booking id doesnot exist")
  else:
    for i in passenger_details:
      if pid==i[0]:
        passenger_details.pop(passenger_details.index(i))
    for i in payment:
      if pid==i[1]:
        payment.pop(payment.index(i))
    print("Successfully your booking has been cancelled!")
    for i in availability:
      if i[1]==train_id:
        i[2]+=1
        break
    

#Railway Reservation System
#default data is stored in the list
train_details=[['234AR','Rajasthan Express','1:00 PM','6:00 PM','Delhi','Jaipur',349],['583Es','Bhopal Shatabdi','5:00 AM','12:00 AM','Delhi','Bhopal',990],['45CD5','Duranta Express','11:30 PM','11:30 AM','Kolkata','Bangalore',1050],['6HA40','Grand Trunk Express','3:00 PM','3:00 PM in 2 days','Delhi','Chennai',1150],['12KW1','Lucknow Mail','7:30 PM','3:00 AM','Lucknow','Delhi',650]]      #train(pnr,train_name,start_time,end_time,start_point,destination,fare)
passenger_details=[[1,'Akarsh Shrivastava',22,7303764800],[2,'Priyanka Ghosh',23,7550113230],[3,'Maadhav Sharma',34,7003046144],[4,'Nayanika Salgaokar',27,8614469829], [5,'Neeta Gaikwad',42,8450056211]]        #passenger_details(id,name,age,phone_no)
availability=[[0,'234AR',117],[1,'583Es',120],[2,'45CD5',120],[3,'6HA40',119],[4,'12KW1',119]]  #availability[id,train_id,vacant_seats]
bookings=[[0,'234AR',1,1],[1,'234AR',2,2],[2,'234AR',3,3],[3,'6HA40',4,1],[4,'12KW1',5,1]]     #bookings[booking_id,train_id,passenger_id,seat_number]
payment=[[0,1,349],[1,2,349],[2,3,349],[3,4,1150],[4,5,650]]   #payment[id,passenger_id,fare]
print("*"*8,"Welcome to Railway Reservation System","*"*8)
while True:
  print("Select option from the menu-")
  s1='1. Want information about train'
  s2='2. Checking Availability of a train'
  s3='3. Want to book a seat in a train'
  s4='4. Want to cancel the booking'
  s5='5. Exit the menu'
  print(s1,s2,s3,s4,s5,sep='\n')
  s=int(input())
  if s==1:
    c=input("Enter PNR number or train name \n")
    train_information(c)
  elif s==2:
    c=input("Enter PNR number or train name \n")
    ck=check_availability(c)
    if ck>0:
      print("Vacant seats are",ck)
    elif ck==0:
      print('No Vacany left in the train')
    elif ck==-1:
      print('You entered wrong PNR or Train name')
  elif s==3:
    Booking()
  elif s==4:
    book_id=input("Enter your booking id \n")
    cancelbook(book_id)
  else:
    break
